# Generated by Django 5.0.4 on 2024-05-01 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equipement', models.AutoField(primary_key=True, serialize=False)),
                ('nom_equipement', models.CharField(max_length=100)),
                ('fabricant', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee_achat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id_medecin', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100)),
                ('adresse_email', models.EmailField(max_length=254)),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenRadiologique',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure_examen', models.DateTimeField()),
                ('resultats', models.TextField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.equipement')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImageRadiologique',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('chemin_acces_image', models.CharField(max_length=255)),
                ('date_heure_creation', models.DateTimeField()),
                ('examen_radiologique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.examenradiologique')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id_rendez_vous', models.AutoField(primary_key=True, serialize=False)),
                ('date_heure_rendez_vous', models.DateTimeField()),
                ('type_examen', models.CharField(max_length=100)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id_worklist', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], max_length=20)),
                ('priorite', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkList.examenradiologique')),
            ],
        ),
    ]
