# Generated by Django 5.0.4 on 2024-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worklist',
            old_name='id_worklist',
            new_name='id',
        ),
    ]
