# Generated by Django 5.0.4 on 2024-05-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkList', '0002_rename_id_worklist_worklist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenradiologique',
            old_name='id_examen',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='id_rendez_vous',
            new_name='id',
        ),
    ]
